# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('is_citizen', models.BooleanField()),
                ('description', models.TextField()),
                ('favourite_language', models.CharField(choices=[('PYT', 'Python'), ('PHP', 'PHP'), ('PRL', 'Perl'), ('PLG', 'Prolog'), ('FTN', 'Fortran'), ('HKL', 'Haskell')], max_length=3)),
                ('years_experience', models.PositiveIntegerField()),
                ('photo', models.FileField(upload_to='photos')),
                ('resume', models.TextField()),
                ('resume_hash', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
