# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='favourite_language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PHP', 'PHP'), ('PRL', 'Perl'), ('PLG', 'Prolog'), ('FTN', 'Fortran'), ('HKL', 'Haskell')], max_length=3),
        ),
    ]
