# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_candidate_resume_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
    ]
